//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaPhim
    {
        public int sttDanhGia { get; set; }
        public string idTaiKhoan { get; set; }
        public string idPhim { get; set; }
        public Nullable<int> soSaoDanhGia { get; set; }
    
        public virtual Phim Phim { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
