//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebsiteCinemaEntities : DbContext
    {
        public WebsiteCinemaEntities()
            : base("name=WebsiteCinemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaiViet> BaiViets { get; set; }
        public virtual DbSet<BinhLuan> BinhLuans { get; set; }
        public virtual DbSet<DanhGiaPhim> DanhGiaPhims { get; set; }
        public virtual DbSet<DiaChiIPDangNhap> DiaChiIPDangNhaps { get; set; }
        public virtual DbSet<DienVienDaoDien> DienVienDaoDiens { get; set; }
        public virtual DbSet<DonDatVe> DonDatVes { get; set; }
        public virtual DbSet<LichChieu> LichChieux { get; set; }
        public virtual DbSet<MaKichHoatTaiKhoan> MaKichHoatTaiKhoans { get; set; }
        public virtual DbSet<NhomTaiKhoan> NhomTaiKhoans { get; set; }
        public virtual DbSet<Phim> Phims { get; set; }
        public virtual DbSet<PhuongThucThanhToan> PhuongThucThanhToans { get; set; }
        public virtual DbSet<QuocGia> QuocGias { get; set; }
        public virtual DbSet<RapPhim> RapPhims { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<TheLoai> TheLoais { get; set; }
        public virtual DbSet<TrangThaiDon> TrangThaiDons { get; set; }
        public virtual DbSet<TrangThaiTaikhoan> TrangThaiTaikhoans { get; set; }
        public virtual DbSet<VaiTroPhim> VaiTroPhims { get; set; }
    }
}
