//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaChiIPDangNhap
    {
        public int sttDiaChi { get; set; }
        public string idTaiKhoan { get; set; }
        public string thietBi { get; set; }
        public string trinhDuyet { get; set; }
        public string ip { get; set; }
        public Nullable<System.DateTime> thoiGian { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
