//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DienVienDaoDien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DienVienDaoDien()
        {
            this.VaiTroPhims = new HashSet<VaiTroPhim>();
        }
    
        public int sttDienVienDaoDien { get; set; }
        public string tenDienVienDaoDien { get; set; }
        public Nullable<bool> gioiTinh { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public string hinhDaiDien { get; set; }
        public Nullable<bool> trangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VaiTroPhim> VaiTroPhims { get; set; }
    }
}
