//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonDatVe
    {
        public string maDatVe { get; set; }
        public string idLichChieu { get; set; }
        public string idTaiKhoan { get; set; }
        public Nullable<int> soLuongVe { get; set; }
        public string gheNgoi { get; set; }
        public Nullable<double> tongThanhToan { get; set; }
        public int sttPhuongThucTT { get; set; }
        public int trangThaiSTT { get; set; }
    
        public virtual LichChieu LichChieu { get; set; }
        public virtual PhuongThucThanhToan PhuongThucThanhToan { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual TrangThaiDon TrangThaiDon { get; set; }
    }
}
