//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichChieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichChieu()
        {
            this.DonDatVes = new HashSet<DonDatVe>();
        }
    
        public string idLichChieu { get; set; }
        public string idPhim { get; set; }
        public Nullable<System.DateTime> thoiGianChieu { get; set; }
        public Nullable<double> giaVe { get; set; }
        public Nullable<bool> trangThai { get; set; }
        public int sttRap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonDatVe> DonDatVes { get; set; }
        public virtual Phim Phim { get; set; }
        public virtual RapPhim RapPhim { get; set; }
    }
}
