//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phim()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.DanhGiaPhims = new HashSet<DanhGiaPhim>();
            this.LichChieux = new HashSet<LichChieu>();
            this.VaiTroPhims = new HashSet<VaiTroPhim>();
            this.TaiKhoans = new HashSet<TaiKhoan>();
            this.TheLoais = new HashSet<TheLoai>();
        }
    
        public string idPhim { get; set; }
        public string tenPhim { get; set; }
        public string trailer { get; set; }
        public int quocGia { get; set; }
        public Nullable<System.DateTime> thoiGian { get; set; }
        public Nullable<System.DateTime> ngayChieu { get; set; }
        public string gioiThieu { get; set; }
        public Nullable<int> thoiLuong { get; set; }
        public string namSanXuat { get; set; }
        public string congTySanXuat { get; set; }
        public string hinhDaiDien { get; set; }
        public Nullable<bool> trangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaPhim> DanhGiaPhims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichChieu> LichChieux { get; set; }
        public virtual QuocGia QuocGia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VaiTroPhim> VaiTroPhims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TheLoai> TheLoais { get; set; }
    }
}
