//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaiTroPhim
    {
        public int sttThanhPhan { get; set; }
        public int sttDVDD { get; set; }
        public string idPhim { get; set; }
        public string tenVaiTro { get; set; }
        public string ghiChu { get; set; }
    
        public virtual DienVienDaoDien DienVienDaoDien { get; set; }
        public virtual Phim Phim { get; set; }
    }
}
